# Generated by Django 5.1.2 on 2024-10-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='audio_file',
            new_name='file',
        ),
    ]
